competition_active: false  # true kui konkurss käib, false kui on läbi saanud
competition_deadline: "18. maiks"
competition_prize: "kuni kahe 3000 euro suuruse stipendiumi"
competition_form: "https://forms.gle/k5jmpDiYJED3Yswt6"
scholars:
  - year: 2007
    winners:
      - name: "Jelena Hartšenko"
        affiliation: "TTÜ"
        link: "https://ee.linkedin.com/in/jelena-hartsenko-b9415334"
      - name: "Mark Kantšukov"
        affiliation: "Tartu Ülikool"
        link: "https://ee.linkedin.com/in/mark-kanchukov-b9ab95a"
      - name: "Aaro Hazak"
        affiliation: "TTÜ"
        link: "https://et.wikipedia.org/wiki/Aaro_Hazak"
  - year: 2008
    winners:
      - name: "Triin Kask"
        affiliation: "Tartu Ülikool"
        link: "https://www.linkedin.com/in/triinkask/"
      - name: "Marili Männik"
        affiliation: "Estonian Business School"
        link: "https://www.linkedin.com/in/marili-m%C3%A4nnik-b7461611/"
      - name: "Margit Vaaks"
        affiliation: "Tallinna Tehnikaülikool"
        link: ""
  - year: 2009
    winners:
      - name: "Teele Alas"
        affiliation: "Amsterdami Ülikool"
        link: "https://www.linkedin.com/in/teele-alas-b0801960/"
      - name: "Madis Reinumägi"
        affiliation: "Reykjaviki Ülikool"
        link: "https://www.linkedin.com/in/madis-reinum%C3%A4gi-01481452/"
      - name: "Oliver Lukason"
        affiliation: "Tartu Ülikool"
        link: "https://www.etis.ee/CV/Oliver_Lukason/est"
  - year: 2010
    winners:
      - name: "Ave Lepik"
        affiliation: "Tartu Ülikool"
        link: "https://www.linkedin.com/in/avelepik/"
      - name: "Madli Pindmaa"
        affiliation: "Copenhagen Business School"
        link: "https://www.linkedin.com/in/madlipindmaa/"
      - name: "Eeva Mauring"
        affiliation: "Helsingi Ülikool"
        link: ""
  - year: 2011
    winners:
      - name: "Aleksei Netšunajev"
        affiliation: "European University Institute"
        link: "https://www.linkedin.com/in/aleksei-netsunajev-804aa0175/"
      - name: "Indrek Seppo"
        affiliation: "Tartu Ülikool"
        link: "https://www.linkedin.com/in/indrek-seppo-a1896220/"
      - name: "Andres Kuusik"
        affiliation: "Tartu Ülikool"
        link: "https://www.linkedin.com/in/andres-kuusik-29527418/"
  - year: 2012
    winners:
      - name: "Priit Jeenas"
        affiliation: "Barcelona Graduate School of Economics"
        link: ""
      - name: "Evelin Viilmann"
        affiliation: "Tallinna Tehnikaülikool"
        link: ""
      - name: "Kärt Rõigas"
        affiliation: "Tartu Ülikool"
        link: ""
  - year: 2013
    winners:
      - name: "Aleksei Fimaier"
        affiliation: "TTÜ"
        link: "https://ee.linkedin.com/in/aleksei-fimaier-25b69025"
      - name: "Anne Põder"
        affiliation: "Eesti Maaülikool"
        link: "https://www.linkedin.com/in/anne-p%C3%B5der-4aa76894/"
      - name: "Eneli Kindsiko"
        affiliation: "Tartu Ülikool"
        link: "https://ee.linkedin.com/in/enelikindsiko"
  - year: 2014
    winners:
      - name: "Karoline Jostov"
        affiliation: "Bocconi Ülikool/SSE"
        link: "https://www.linkedin.com/in/karoline-j-a68a2b48/"
      - name: "Sten Sonts"
        affiliation: "HEC Paris"
        link: "https://uk.linkedin.com/in/sten-sonts-55283737"
      - name: "Jürgen Kaevats"
        affiliation: "SSE"
        link: "https://www.linkedin.com/in/j%C3%BCrgen-kaevats-119b1041/"
  - year: 2015
    winners:
      - name: "Martin Lumiste"
        affiliation: "Toulouse"
        link: "https://ee.linkedin.com/in/martin-lumiste-558748ab"
      - name: "Sven Sabas"
        affiliation: "LSE"
        link: "https://uk.linkedin.com/in/sven-sabas-90613066"
      - name: "Heili Hein"
        affiliation: "TTÜ"
        link: ""
  - year: 2016
    winners:
      - name: "Sander Veges"
        affiliation: "Fudan University"
        link: "https://cn.linkedin.com/in/sander-veges-770a899a"
      - name: "Renee Pesor"
        affiliation: "EBS"
        link: "https://ee.linkedin.com/in/renee-pesor-42874343"
      - name: "Jelena Komendantova"
        affiliation: "TTÜ"
        link: ""
  - year: 2017
    winners:
      - name: "Janely Põllumägi"
        affiliation: "TTÜ"
        link: "https://www.linkedin.com/in/janely-p%C3%B5llum%C3%A4gi-67b27483/"
      - name: "Laura Saar"
        affiliation: "University of Strathclyde"
        link: "https://www.linkedin.com/in/laura-saar-544379b7/"
      - name: "Marko Virkebau"
        affiliation: "TTÜ"
        link: "https://www.linkedin.com/in/marko-virkebau-3466651b/"
  - year: 2018
    winners:
      - name: "Kristjan Liivamägi"
        affiliation: "TTÜ"
        link: "https://www.linkedin.com/in/kristjanliivamagi/"
      - name: "Triinu Tapver"
        affiliation: "TTÜ"
        link: "https://www.linkedin.com/in/triinu-tapver-b53030153/"
      - name: "Eric Keskpaik"
        affiliation: "Tartu Ülikool"
        link: "https://www.linkedin.com/in/eric-keskpaik-095738b8/"
  - year: 2019
    winners:
      - name: "Indrek Viires"
        affiliation: "TalTech"
        link: "https://www.linkedin.com/in/indrek-viires-8512361a4/"
      - name: "Airiin Laaneväli"
        affiliation: "Tartu Ülikool"
        link: "https://www.linkedin.com/in/airiin-laanev%C3%A4li-78589239/"
      - name: "Mari-Liis Kukk"
        affiliation: "TalTech"
        link: ""
  - year: 2020
    winners:
      - name: "Helery Tasane"
        affiliation: "TalTech"
        link: "https://ee.linkedin.com/in/helery-tasane-10068a80"
      - name: "Hanna-Stina Sonts"
        affiliation: "HEC Paris"
        link: "https://www.linkedin.com/in/hanna-stina-sonts-3011a594/"
  - year: 2021
    winners:
      - name: "Katri Urke"
        affiliation: "TalTech"
        link: "https://www.linkedin.com/in/katri-urke-651a1b171/"
      - name: "Pauline Kommer"
        affiliation: "TalTech"
        link: "https://www.linkedin.com/in/pauline-kommer-bb9924213/"
      - name: "Asso Kasuk"
        affiliation: "Tartu Ülikool"
        link: "https://www.linkedin.com/in/asso-kasuk-52b068152/"
  - year: 2022
    winners:
      - name: "Laura Helena Kivi"
        affiliation: "Tartu Ülikool"
        link: ""
      - name: "Miina Hõbenael"
        affiliation: "TalTech"
        link: ""
      - name: "Vladislav Fjodorov"
        affiliation: "TalTech"
        link: ""
  - year: 2023
    winners:
      - name: "Kristjan Pulk"
        affiliation: "Tartu Ülikool"
        link: "https://www.linkedin.com/in/kristjan-pulk-aa2884240/"
      - name: "Gerda Kirpson"
        affiliation: "TalTech"
        link: "https://www.linkedin.com/in/gerda-kirpson-9b8a9712a/"
      - name: "Sofia Kruusalu"
        affiliation: "TalTech"
        link: "https://www.linkedin.com/in/sofia-kruusalu-6a466a1b5/"
  - year: 2024
    winners:
      - name: "Mathias Juust"
        affiliation: "Tartu Ülikool"
        link: "https://www.linkedin.com/in/mathias-juust-618615143/"
      - name: "Ann Merit Toiger"
        affiliation: "TalTech"
        link: "https://www.linkedin.com/in/ann-merit-toiger-b0b5a822b/"
      - name: "Liina Rebane"
        affiliation: "TalTech"
        link: "https://www.linkedin.com/in/liina-rebane-159985267/"
  - year: 2025
    winners:
      - name: "Merilin Martinson"
        affiliation: "University College London"
        link: "https://www.linkedin.com/in/merilin-martinson/"
      - name: "Marit Priisalu"
        affiliation: "TalTech"
        link: "https://ee.linkedin.com/in/marit-p-7892282b2/"
        
        
